USE QLOTO
CREATE TABLE ADMIN( Username NVARCHAR(20),pass INT,chucvu NVARCHAR(20))

CREATE TABLE THONGTINHOPDONG(SOPHIEU INT, SOHOPDONG NVARCHAR(15), LOAIHINH NVARCHAR(15),
 NGAYTHUE DATE, NGAYTRA DATE, NGAYKYHOPDONG DATE, BAIKINHDOANH NVARCHAR(50), MASOTHUE CHAR(20),THANHTIEN FLOAT ,GHICHU NVARCHAR(50))

CREATE TABLE KHACHHANG(HOTEN NVARCHAR(50), DIACHI NVARCHAR(100), STD CHAR(20), CMND CHAR(20), NGAYCAPCMND DATE,
 NOICAPCMND NVARCHAR(50), SOGPLX CHAR(20), NGAYCAPGPLX DATE, NOICAPGPLX NVARCHAR(50), NGHENGHIEP NVARCHAR(50))

CREATE TABLE XE(NHANHIEU NVARCHAR(50), TENXE NVARCHAR(50),BIENSO INT,DUNGTICH INT,XELOAI NVARCHAR(20))

CREATE TABLE LOAIHINH(THUENGAY INT,THUETHANG INT,THOIGIANTHUE INT)

CREATE TABLE DAILY(TENDAILY NVARCHAR(50),MASODAILY INT,DIACHI NVARCHAR(50),SDT INT)